# Title and description will feature on the site!
title: Abhishek Anand
description: First year MS in CS (AI) student at USC.
baseurl: "" # The site subpath -- for example, "/blog"
url: "" # http://example.com for example.

# Want to give people your email?
email: anandabh@usc.edu

# Enter your GitHub username.
github: abhishekanand1710
linkedin_username: abhishekanand1710

permalink: /:title
